import {execFileSync} from 'node:child_process';
import {expect,test} from '@playwright/test';
import { releaseSyntheticAdminSession } from './synthetic-admin-session';

test.afterEach(async ({ page }) => {
    await releaseSyntheticAdminSession(page);
});
const brand='MT75 P02 Linked Brand';
const edited='MT75 P02 Linked Brand Updated';
const product='MT75 P02 Linked Product';
const endpoint='/internal/admin/pos/master-data';
test('P02 actual product retains original brand after option edit, while used option cannot be deleted',async({page})=>{
    test.setTimeout(60000);
    execFileSync('php',['artisan','db:seed','--class=Database\\Seeders\\PosMasterDataLinkedE2eSeeder','--env=testing','--force'],{cwd:process.cwd(),stdio:'inherit'});
    await page.goto('/internal/admin/pos/login');
    await page.getByTestId('login-email').fill('e2e-protected-owner@example.invalid');
    await page.getByTestId('login-password').fill('SyntheticPass123!');
    await page.getByTestId('login-submit').click(); await page.waitForURL('**/internal/admin/pos');
    await expect(page.getByTestId('outlet-select')).toBeVisible();
    const selected=page.waitForResponse(r=>r.url().endsWith('/internal/admin/outlets/select')&&r.request().method()==='POST');
    await page.getByTestId('outlet-select').selectOption({label:'MT75 P02 Linked Outlet'});
    expect((await selected).status()).toBe(200);
    await page.goto('/internal/admin/pos/workspace/master-data');
    await expect(page.getByTestId('master-data-workspace')).toBeVisible();
    await page.getByTestId('master-label').fill(brand);
    const created=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');
    await page.getByTestId('master-create').click(); const createdResponse=await created; expect(createdResponse.status()).toBe(200);
    const optionId=(await createdResponse.json()).data.id as number;
    await page.goto('/internal/admin/pos/workspace/inventory');
    const definition=page.getByRole('heading',{name:'Product definition'}).locator('..');
    await expect(definition).toBeVisible();
    await definition.getByPlaceholder('Product name').fill(product);
    await definition.locator('select').first().selectOption({label:'Accessories'});
    await definition.locator('select').nth(1).selectOption({label:brand});
    await definition.getByPlaceholder('Purchase price').fill('1.00');
    await definition.getByPlaceholder('Sale price').fill('2.00');
    const saved=page.waitForResponse(r=>r.url().endsWith('/internal/admin/pos/inventory/products')&&r.request().method()==='POST');
    await page.getByTestId('product-save').click(); const productResponse=await saved;
    expect(productResponse.status()).toBe(200);
    const productId=(await productResponse.json()).data.id as string;
    await expect(page.getByTestId('inventory-brand-history-'+productId)).toContainText('Original brand: '+brand);
    await page.goto('/internal/admin/pos/workspace/master-data');
    const row=page.getByTestId('master-row-mt75_p02_linked_brand');
    await expect(row).toContainText('1 recorded uses');
    await expect(row.getByRole('button',{name:'Delete unused'})).toHaveCount(0);
    await row.getByRole('button',{name:'Edit'}).click();
    await page.getByTestId('master-edit-label').fill(edited);
    const renamed=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');
    await page.getByTestId('master-edit-save').click(); expect((await renamed).status()).toBe(200);
    await expect(row).toContainText(edited);
    const rejected=await page.evaluate(async(optionId:number)=>{
        const tokenResponse=await fetch('/internal/admin/auth/csrf-cookie',{credentials:'same-origin',headers:{Accept:'application/json'}});
        const body=await tokenResponse.json() as {data:{csrf_token:string}};
        const response=await fetch('/internal/admin/pos/master-data',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':body.data.csrf_token},body:JSON.stringify({list:'product_brand',action:'delete',id:optionId})});
        return response.status;
    },optionId);
    expect(rejected).toBe(422);
    await page.goto('/internal/admin/pos/workspace/inventory');
    await page.getByTestId('pos-lookup').fill(product);
    await page.getByRole('button',{name:'Search',exact:true}).click();
    const history=page.getByTestId('inventory-brand-history-'+productId);
    await expect(history).toContainText('Original brand: '+brand);
    await expect(history).toContainText('Current brand: '+edited);
    await page.goto('/internal/admin/pos/workspace/master-data');
    await expect(page.getByTestId('master-row-mt75_p02_linked_brand')).toContainText('1 recorded uses');
    await expect(page.getByTestId('master-row-mt75_p02_linked_brand').getByRole('button',{name:'Delete unused'})).toHaveCount(0);
});