import {expect,test} from '@playwright/test';

test('D01 operator opt-in stores only category in current tab and clears on logout or outlet switch',async({page,browser})=>{
    test.setTimeout(105000);
    const signIn=async(email:string)=>{
        await page.goto('/internal/admin/pos/login');
        await page.getByTestId('login-email').fill(email);
        await page.getByTestId('login-password').fill('SyntheticPass123!');
        await page.getByTestId('login-submit').click();
        await page.waitForURL('**/internal/admin/pos');
    };
    const stored=()=>page.evaluate(()=>window.sessionStorage.getItem('mobist.pos.search-tab.v1'));
    await signIn('e2e-pref-owner@example.invalid');
    await page.goto('/internal/admin/pos/portal-preferences');
    await page.getByTestId('pref-remember_search').check();
    const save=page.waitForResponse(r=>r.url().endsWith('/internal/admin/pos/portal-preferences')&&r.request().method()==='PUT');
    await page.getByTestId('portal-preferences-save').click();
    expect((await save).status()).toBe(200);
    await page.goto('/internal/admin/pos/workspace/invoices');
    await expect(page.getByTestId('history-tab-opt-in')).not.toBeChecked();
    expect(await stored()).toBeNull();
    await page.getByTestId('history-tab-opt-in').check();
    await page.getByTestId('history-category').selectOption('item');
    await page.getByTestId('history-search').fill('42101-1234567-1');
    await page.reload();
    await expect(page.getByTestId('history-category')).toHaveValue('item');
    await expect(page.getByTestId('history-search')).toHaveValue('');
    expect(await stored()).not.toContain('42101-1234567-1');
    await page.goto('/internal/admin/pos/workspace/warranty');
    await expect(page.getByTestId('history-tab-opt-in')).toBeChecked();
    await page.getByTestId('history-category').selectOption('product');
    await page.reload();
    await expect(page.getByTestId('history-category')).toHaveValue('product');
    await page.goto('/internal/admin/pos/workspace/claims');
    await page.getByTestId('intake-category').selectOption('product');
    await page.getByTestId('intake-query').fill('03001234567');
    await page.reload();
    await expect(page.getByTestId('intake-category')).toHaveValue('product');
    await expect(page.getByTestId('intake-query')).toHaveValue('');
    expect(await stored()).not.toContain('03001234567');
    await page.getByTestId('logout').click();
    await page.waitForURL('**/internal/admin/pos/login');
    expect(await stored()).toBeNull();
    await page.evaluate(()=>window.sessionStorage.setItem('mobist.pos.search-tab.v1', 'stale-session-fixture'));
    await page.reload();
    expect(await stored()).toBeNull();
    const inventoryContext=await browser.newContext();
    const inventoryPage=await inventoryContext.newPage();
    await inventoryPage.goto('/internal/admin/pos/login');
    await inventoryPage.getByTestId('login-email').fill('e2e-iw-inventory@example.invalid');
    await inventoryPage.getByTestId('login-password').fill('SyntheticPass123!');
    await inventoryPage.getByTestId('login-submit').click();
    await inventoryPage.waitForURL('**/internal/admin/pos');
    await expect(inventoryPage.getByTestId('outlet-required')).toBeVisible();
    const inventoryStored=()=>inventoryPage.evaluate(()=>window.sessionStorage.getItem('mobist.pos.search-tab.v1'));
    const firstSelection=inventoryPage.waitForResponse(r=>r.url().endsWith('/internal/admin/outlets/select')&&r.request().method()==='POST');
    await inventoryPage.getByTestId('outlet-select').selectOption({label:'E2E Sales Outlet'});
    expect((await firstSelection).status()).toBe(200);
    await inventoryPage.waitForURL('**/internal/admin/pos');
    const inventoryRoute=await inventoryPage.goto('/internal/admin/pos/workspace/inventory');
    expect(inventoryRoute?.status()).toBe(200);
    await expect(inventoryPage.getByTestId('inventory-tab-opt-in')).not.toBeChecked();
    await inventoryPage.getByTestId('inventory-tab-opt-in').check();
    await inventoryPage.getByTestId('inventory-category').selectOption('brand');
    await inventoryPage.getByTestId('pos-lookup').fill('356789012345678');
    await inventoryPage.reload();
    await expect(inventoryPage.getByTestId('inventory-category')).toHaveValue('brand');
    await expect(inventoryPage.getByTestId('pos-lookup')).toHaveValue('');
    expect(await inventoryStored()).not.toContain('356789012345678');
    const selection=inventoryPage.waitForResponse(r=>r.url().endsWith('/internal/admin/outlets/select')&&r.request().method()==='POST');
    await inventoryPage.getByTestId('outlet-select').selectOption({label:'E2E Inventory Outlet'});
    expect((await selection).status()).toBe(200);
    await inventoryPage.waitForURL('**/internal/admin/pos');
    expect(await inventoryStored()).toBeNull();
    await inventoryPage.goto('/internal/admin/pos/workspace/inventory');
    await expect(inventoryPage.getByTestId('inventory-tab-opt-in')).not.toBeChecked();
    await expect(inventoryPage.getByTestId('inventory-category')).toHaveValue('all');
    await inventoryPage.getByTestId('logout').click();
    await inventoryPage.waitForURL('**/internal/admin/pos/login');
    expect(await inventoryStored()).toBeNull();
    await inventoryContext.close();
});
