import { Head, Link } from '@inertiajs/react';
import { FormEvent, useCallback, useEffect, useState } from 'react';

type Summary = { filters:{from:string;to:string;category:string|null;product:string|null;outlet:string|null}; orders:number;paid_orders:number;pending_or_unpaid_orders:number; paid_reconciliation_orders:number; paid_commerce_order_total:string; paid_digital_order_total:string; paid_order_total:string; average_paid_order_total:string; paid_order_percentage:string; digital_paid_order_share:string; returned_orders:number; refunded_orders:number; payment_status_count:Record<string,number>; order_type_count:Record<string,number>; service_requests:number;new_requests:number;quotes:number;paid_quotes:number;approved_unpaid_quotes:number;quote_paid_percentage:string; gateway_attempt_count:Record<string,number>; recent_orders:Array<{order_number:string;order_type:string;payment_status:string;created_at:string}>; recent_requests:Array<{reference:string;status:string;created_at:string}>; top_products:Array<{title:string;units:number;line_total_before_order_discounts:string}>; daily:Array<{day:string;orders:number;paid_order_total:string}>; definition:string };
type Export = {filename:string;csv:string;count:number};
async function get<T>(url:string):Promise<T>{
    const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json'},cache:'no-store'});
    const body=await response.json().catch(()=>({})) as {data?:T;message?:string;errors?:Record<string,string[]>};
    if(!response.ok||!body.data)throw new Error(body.errors?Object.values(body.errors).flat()[0]:(body.message??'Report unavailable.'));
    return body.data;
}
export default function WebsitePerformance({identity}:{identity:{name:string;job_title:string|null}}){
    const [from,setFrom]=useState('');const [to,setTo]=useState('');const [category,setCategory]=useState('');
    const [product,setProduct]=useState('');const [outlet,setOutlet]=useState('');
    const [applied,setApplied]=useState('');const [data,setData]=useState<Summary|null>(null);
    const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
    const load=useCallback(async()=>{setData(await get<Summary>('/internal/admin/website-performance/data'+(applied?'?'+applied:'')));},[applied]);
    useEffect(()=>{void load().catch(error=>setMessage(error instanceof Error?error.message:'Report unavailable.'));},[load]);
    const params=()=>new URLSearchParams(Object.entries({from,to,category,product,outlet}).filter(([,value])=>value!==''));
    const apply=(event:FormEvent)=>{event.preventDefault();setMessage('');setApplied(params().toString());};
    const exportCsv=async()=>{setBusy(true);setMessage('');try{const response=await get<Export>('/internal/admin/website-performance/orders.csv'+(applied?'?'+applied:''));
        const objectUrl=URL.createObjectURL(new Blob([response.csv],{type:'text/csv;charset=utf-8'}));
        const anchor=document.createElement('a');anchor.href=objectUrl;anchor.download=response.filename;anchor.click();URL.revokeObjectURL(objectUrl);
        setMessage('Exported '+response.count+' Website order(s).');
    }catch(error){setMessage(error instanceof Error?error.message:'Export failed.');}finally{setBusy(false);}};
    return <><Head title="Website performance"/><main className="min-h-screen bg-slate-50 p-4 text-slate-950 sm:p-8"><div className="mx-auto max-w-6xl space-y-5">
        <header className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5"><div><h1 className="text-2xl font-semibold">Website performance</h1><p className="text-sm text-slate-600">{identity.name} · Read-only combined commerce and digital-order summary</p></div><Link href="/internal/admin/platform" className="rounded border px-3 py-2 text-sm">Back to Platform</Link></header>
        <p className="text-sm text-slate-600">Paid order face totals are not settled revenue or profit. Orders requiring payment reconciliation stay separate. Choose a date window up to 366 days; blank dates show the most recent 30 days.</p>
        <form onSubmit={apply} data-testid="website-performance-filters" className="grid min-w-0 gap-3 rounded-xl border bg-white p-4 sm:grid-cols-3">
            <label className="text-sm">From<input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 w-full min-w-0 rounded border p-2"/></label>
            <label className="text-sm">To<input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 w-full min-w-0 rounded border p-2"/></label>
            <label className="text-sm">Category<select aria-label="Product category" value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">All categories</option>{['mobile_phone','tablet','accessory'].map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label>
            <label className="text-sm sm:col-span-2">Product ID (optional)<input value={product} onChange={e=>setProduct(e.target.value)} placeholder="Exact product UUID" className="mt-1 w-full min-w-0 rounded border p-2"/></label>
            <label className="text-sm">Outlet ID (optional)<input value={outlet} onChange={e=>setOutlet(e.target.value)} placeholder="Exact outlet UUID" className="mt-1 w-full min-w-0 rounded border p-2"/></label>
            <div className="flex flex-wrap gap-2 sm:col-span-3"><button className="rounded bg-slate-950 px-4 py-2 text-sm text-white">Apply filters</button><button type="button" disabled={busy||!data} onClick={()=>void exportCsv()} className="rounded border px-4 py-2 text-sm disabled:opacity-40">Export combined order CSV</button></div>
        </form>
        {message&&<p role="status" className="rounded border bg-white p-3 text-sm">{message}</p>}
        {data&&<><section data-testid="website-performance-summary" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {([['Orders',data.orders],['Paid orders',data.paid_orders],['Pending / unpaid',data.pending_or_unpaid_orders],['Payment reconciliation',data.paid_reconciliation_orders],['Paid commerce face total (PKR)',data.paid_commerce_order_total],['Paid digital face total (PKR)',data.paid_digital_order_total],['Combined paid face total (PKR)',data.paid_order_total],['Average paid order (PKR)',data.average_paid_order_total],['Paid-order rate (%)',data.paid_order_percentage],['Digital paid-order share (%)',data.digital_paid_order_share],['Returns',data.returned_orders],['Refund-status orders',data.refunded_orders],['Service requests',data.service_requests],['New service requests',data.new_requests],['Quotes',data.quotes],['Paid quotes',data.paid_quotes],['Approved unpaid quotes',data.approved_unpaid_quotes],['Paid quote share (%)',data.quote_paid_percentage]] as Array<[string,string|number]>).map(([label,value])=><article key={label} className="min-w-0 rounded border bg-white p-3"><h2 className="text-xs text-slate-600">{label}</h2><p className="mt-1 break-all text-xl font-semibold">{value}</p></article>)}
        </section><p className="text-xs text-slate-600">{data.definition}</p>
            <div className="grid gap-4 md:grid-cols-2"><section className="min-w-0 rounded border bg-white p-4"><h2 className="font-semibold">Recent daily orders / paid face totals</h2><div className="mt-3 max-h-72 overflow-auto text-sm">{data.daily.map(row=><p key={row.day} className="border-b py-1">{row.day}: {row.orders} order(s); PKR {row.paid_order_total}</p>)}</div></section>
                <section className="min-w-0 rounded border bg-white p-4"><h2 className="font-semibold">Paid order product lines</h2><p className="text-xs text-slate-600">Line totals before order-level discounts, not net product revenue.</p><div className="mt-3 space-y-2 text-sm">{data.top_products.map((row,i)=><p key={i} className="border-b py-1">{row.title}: {row.units} units · PKR {row.line_total_before_order_discounts}</p>)}{data.top_products.length===0&&'No product sales in range.'}</div></section></div>
            <div className="grid gap-4 sm:grid-cols-2"><section className="rounded border bg-white p-4"><h2 className="font-semibold">Recent Website orders</h2>{data.recent_orders.map(row=><p key={row.order_number} className="text-sm">{row.order_number}: {row.order_type} · {row.payment_status}</p>)}</section><section className="rounded border bg-white p-4"><h2 className="font-semibold">Recent service requests</h2>{data.recent_requests.map(row=><p key={row.reference} className="text-sm">{row.reference}: {row.status}</p>)}</section></div>
            <div className="grid gap-4 sm:grid-cols-3"><section className="rounded border bg-white p-4"><h2 className="font-semibold">Latest gateway attempt per order</h2><p className="text-xs text-slate-600">Recorded attempt selection, not verified settlement.</p>{Object.entries(data.gateway_attempt_count).map(([gateway,count])=><p key={gateway} className="text-sm">{gateway}: {count}</p>)}</section><section className="rounded border bg-white p-4"><h2 className="font-semibold">Payment status counts</h2>{Object.entries(data.payment_status_count).map(([status,count])=><p key={status} className="text-sm">{status}: {count}</p>)}</section><section className="rounded border bg-white p-4"><h2 className="font-semibold">Order type counts</h2>{Object.entries(data.order_type_count).map(([kind,count])=><p key={kind} className="text-sm">{kind}: {count}</p>)}</section></div>
        </>}
    </div></main></>;
}
