<?php

// MT-2.1: adapted from pinned source schemas; no source data or backfills execute here.
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {

        Schema::create('account_sessions', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('guard', 20)->collation('utf8mb4_bin');
            $table->bigInteger('account_id')->unsigned();
            $table->string('device_id', 64);
            $table->string('device_type', 16);
            $table->string('location_key', 128)->collation('utf8mb4_bin');
            $table->string('ip_address', 45)->nullable();
            $table->string('session_id', 255);
            $table->text('user_agent')->nullable();
            $table->dateTime('last_activity', 6);
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['guard', 'account_id', 'last_activity'], 'mt21_account_sessions_0');
            $table->unique(['guard', 'account_id', 'device_id'], 'mt21_account_sessions_1');
            $table->index(['session_id'], 'mt21_account_sessions_2');
        });

        Schema::create('admins', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('name', 255);
            $table->string('email', 255);
            $table->dateTime('email_verified_at', 6)->nullable();
            $table->string('password', 255);
            $table->boolean('status')->default('0');
            $table->string('remember_token', 100)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('profile_photo', 255)->nullable();
            $table->json('permissions')->nullable();
            $table->dateTime('archived_at', 6)->nullable();
            $table->unique(['email'], 'mt21_admins_0');
        });

        Schema::create('backup_records', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('outlet_id')->unsigned()->nullable();
            $table->string('scope', 40);
            $table->json('shop_ids')->nullable();
            $table->string('trigger', 30)->default('manual');
            $table->string('requested_by_type', 40);
            $table->bigInteger('requested_by_id')->unsigned()->nullable();
            $table->string('status', 30)->default('processing');
            $table->string('filename', 255);
            $table->string('path', 255)->nullable();
            $table->bigInteger('size_bytes')->unsigned()->nullable();
            $table->string('checksum', 64)->nullable();
            $table->string('remote_status', 30)->default('not_configured');
            $table->string('remote_path', 255)->nullable();
            $table->text('error_message')->nullable();
            $table->dateTime('completed_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['requested_by_type', 'requested_by_id'], 'mt21_backup_records_0');
            $table->index(['outlet_id', 'created_at'], 'mt21_backup_records_1');
            $table->index(['status'], 'mt21_backup_records_2');
        });

        Schema::create('claims', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('product_id')->unsigned();
            $table->bigInteger('invoice_id')->unsigned();
            $table->bigInteger('outlet_id')->unsigned();
            $table->integer('quantity');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('claim_number', 40)->nullable();
            $table->bigInteger('sale_id')->unsigned()->nullable();
            $table->bigInteger('stock_unit_id')->unsigned()->nullable();
            $table->string('status', 40)->default('received');
            $table->text('issue_description')->nullable();
            $table->string('received_condition', 150)->nullable();
            $table->string('accessories_received', 500)->nullable();
            $table->string('assigned_to', 150)->nullable();
            $table->text('diagnosis')->nullable();
            $table->text('resolution')->nullable();
            $table->text('internal_notes')->nullable();
            $table->dateTime('received_at', 6)->nullable();
            $table->dateTime('expected_completion_at', 6)->nullable();
            $table->dateTime('resolved_at', 6)->nullable();
            $table->dateTime('delivered_at', 6)->nullable();
            $table->boolean('customer_satisfied')->nullable();
            $table->boolean('follow_up_required')->default('0');
            $table->dateTime('follow_up_at', 6)->nullable();
            $table->text('follow_up_notes')->nullable();
            $table->json('activity_log')->nullable();
            $table->bigInteger('handled_by_admin_id')->unsigned()->nullable();
            $table->string('handled_by_name', 255)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['claim_number'], 'mt21_claims_0');
            $table->index(['status'], 'mt21_claims_1');
            $table->unique(['public_id'], 'mt21_claims_2');
        });

        Schema::create('legacy_integration_requests', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('reservation_id')->unsigned()->nullable();
            $table->string('endpoint', 120);
            $table->uuid('idempotency_key')->collation('utf8mb4_bin');
            $table->uuid('request_id')->nullable();
            $table->char('request_hash', 64)->collation('utf8mb4_bin');
            $table->string('status', 20)->default('processing');
            $table->smallInteger('response_status')->unsigned()->nullable();
            $table->json('response_payload')->nullable();
            $table->dateTime('completed_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['endpoint', 'idempotency_key'], 'mt21_legacy_integration_requests_0');
            $table->index(['status', 'created_at'], 'mt21_legacy_integration_requests_1');
        });

        Schema::create('invoices', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('outlet_id')->unsigned();
            $table->decimal('total_bill', 19, 2);
            $table->decimal('discount', 19, 2)->default('0');
            $table->decimal('final_bill', 19, 2);
            $table->string('customer_name', 255)->nullable();
            $table->string('customer_phone', 255)->nullable();
            $table->text('customer_info')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('customer_cnic', 15)->nullable();
            $table->bigInteger('salesperson_admin_id')->unsigned()->nullable();
            $table->string('salesperson_name', 255)->nullable();
            $table->json('business_snapshot')->nullable();
            $table->string('invoice_number', 50)->nullable();
            $table->json('warranty_terms_snapshot')->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->bigInteger('customer_id')->unsigned()->nullable();
            $table->bigInteger('order_id')->unsigned()->nullable();
            $table->char('currency', 3)->collation('utf8mb4_bin')->default('PKR');
            $table->index(['customer_cnic'], 'mt21_invoices_0');
            $table->unique(['invoice_number'], 'mt21_invoices_1');
            $table->unique(['public_id'], 'mt21_invoices_2');
            $table->unique(['order_id'], 'mt21_invoices_3');
            $table->unique(['id', 'outlet_id'], 'mt21_invoices_4');
        });

        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->string('email', 255);
            $table->string('token', 255)->collation('utf8mb4_bin');
            $table->dateTime('created_at', 6)->nullable();
            $table->primary(['email'], 'mt21_password_reset_tokens_0');
        });

        Schema::create('personal_access_tokens', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('tokenable_type', 255)->collation('utf8mb4_bin');
            $table->bigInteger('tokenable_id')->unsigned();
            $table->string('name', 255);
            $table->string('token', 64)->collation('utf8mb4_bin');
            $table->text('abilities')->nullable();
            $table->dateTime('last_used_at', 6)->nullable();
            $table->dateTime('expires_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['token'], 'mt21_personal_access_tokens_0');
            $table->index(['tokenable_type', 'tokenable_id'], 'mt21_personal_access_tokens_1');
        });

        Schema::create('pos_audit_logs', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('actor_type', 40);
            $table->bigInteger('actor_id')->unsigned()->nullable();
            $table->string('actor_name', 180)->nullable();
            $table->string('actor_email', 190)->nullable();
            $table->bigInteger('outlet_id')->unsigned()->nullable();
            $table->string('action', 180);
            $table->string('method', 10);
            $table->string('path', 500);
            $table->json('payload')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->smallInteger('status_code')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['action'], 'mt21_pos_audit_logs_0');
            $table->index(['actor_id'], 'mt21_pos_audit_logs_1');
            $table->index(['actor_type'], 'mt21_pos_audit_logs_2');
            $table->index(['created_at'], 'mt21_pos_audit_logs_3');
        });

        Schema::create('pos_configuration_revisions', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('domain', 80)->collation('utf8mb4_bin');
            $table->integer('version')->unsigned();
            $table->string('state', 20);
            $table->json('snapshot');
            $table->string('created_by_type', 40)->nullable();
            $table->bigInteger('created_by_id')->unsigned()->nullable();
            $table->string('published_by_type', 40)->nullable();
            $table->bigInteger('published_by_id')->unsigned()->nullable();
            $table->dateTime('published_at', 6)->nullable();
            $table->bigInteger('restored_from_revision_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['created_by_type', 'created_by_id'], 'mt21_pos_configuration_revisions_0');
            $table->index(['domain'], 'mt21_pos_configuration_revisions_1');
            $table->index(['domain', 'state'], 'mt21_pos_configuration_revisions_2');
            $table->unique(['domain', 'version'], 'mt21_pos_configuration_revisions_3');
            $table->index(['published_by_type', 'published_by_id'], 'mt21_pos_configuration_revisions_4');
            $table->index(['state'], 'mt21_pos_configuration_revisions_5');
        });

        Schema::create('pos_master_data_options', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('list_key', 80)->collation('utf8mb4_bin');
            $table->string('code', 100)->collation('utf8mb4_bin');
            $table->string('label', 160);
            $table->integer('sort_order')->unsigned()->default('0');
            $table->boolean('is_active')->default('1');
            $table->dateTime('archived_at', 6)->nullable();
            $table->string('created_by_type', 40)->nullable();
            $table->bigInteger('created_by_id')->unsigned()->nullable();
            $table->string('updated_by_type', 40)->nullable();
            $table->bigInteger('updated_by_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->json('metadata')->nullable();
            $table->unique(['list_key', 'code'], 'mt21_pos_master_data_options_0');
            $table->index(['list_key', 'is_active', 'archived_at', 'sort_order'], 'mt21_pos_master_data_options_1');
        });

        Schema::create('pos_master_data_usages', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('master_data_option_id')->unsigned();
            $table->string('usage_type', 120);
            $table->string('usage_id', 120);
            $table->string('usage_field', 80);
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['master_data_option_id', 'usage_type', 'usage_id', 'usage_field'], 'mt21_pos_master_data_usages_0');
        });

        Schema::create('pos_media_assets', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('disk', 60)->default('public');
            $table->string('path', 500);
            $table->string('original_name', 255);
            $table->string('mime_type', 100);
            $table->string('extension', 12);
            $table->bigInteger('byte_size')->unsigned();
            $table->integer('width')->unsigned();
            $table->integer('height')->unsigned();
            $table->decimal('aspect_ratio', 12, 6);
            $table->char('sha256', 64);
            $table->string('alt_text', 500)->nullable();
            $table->string('status', 20)->default('active');
            $table->string('uploaded_by_type', 40)->nullable();
            $table->bigInteger('uploaded_by_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['path'], 'mt21_pos_media_assets_0');
            $table->index(['sha256'], 'mt21_pos_media_assets_1');
            $table->index(['status'], 'mt21_pos_media_assets_2');
            $table->index(['uploaded_by_type', 'uploaded_by_id'], 'mt21_pos_media_assets_3');
        });

        Schema::create('pos_media_usages', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('media_asset_id')->unsigned();
            $table->string('usage_domain', 80);
            $table->string('usage_key', 160)->collation('utf8mb4_bin');
            $table->string('entity_type', 160)->nullable();
            $table->bigInteger('entity_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['media_asset_id', 'usage_domain', 'usage_key', 'entity_type', 'entity_id'], 'mt21_pos_media_usages_0');
            $table->index(['entity_type', 'entity_id'], 'mt21_pos_media_usages_1');
            $table->index(['usage_domain'], 'mt21_pos_media_usages_2');
        });

        Schema::create('pos_settings', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('key', 140)->collation('utf8mb4_bin');
            $table->text('value')->nullable();
            $table->string('group', 80)->default('general');
            $table->string('label', 180);
            $table->string('input_type', 30)->default('text');
            $table->integer('sort_order')->unsigned()->default('0');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['group'], 'mt21_pos_settings_0');
            $table->unique(['key'], 'mt21_pos_settings_1');
        });

        Schema::create('product_imeis', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('product_id')->unsigned();
            $table->string('imei', 50)->collation('utf8mb4_bin');
            $table->enum('status', ['in_stock', 'sold'])->default('in_stock');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->integer('device_no')->unsigned()->default('1');
            $table->tinyInteger('slot_no')->unsigned()->default('1');
            $table->bigInteger('invoice_id')->unsigned()->nullable();
            $table->dateTime('sold_at', 6)->nullable();
            $table->bigInteger('sale_id')->unsigned()->nullable();
            $table->bigInteger('stock_unit_id')->unsigned()->nullable();
            $table->index(['product_id', 'device_no', 'slot_no', 'status'], 'mt21_product_imeis_0');
            $table->index(['imei', 'status'], 'mt21_product_imeis_1');
            $table->index(['product_id', 'status'], 'mt21_product_imeis_2');
            $table->index(['sale_id'], 'mt21_product_imeis_3');
            $table->index(['stock_unit_id', 'status'], 'mt21_product_imeis_4');
        });

        Schema::create('products', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('name', 255);
            $table->decimal('price', 19, 2);
            $table->string('image', 255)->nullable();
            $table->bigInteger('outlet_id')->unsigned();
            $table->text('description')->nullable();
            $table->integer('warranty_unit')->nullable();
            $table->integer('warranty_duration')->nullable();
            $table->integer('qty')->default('0');
            $table->integer('sold_qty')->default('0');
            $table->boolean('isDeleted')->default('0');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->boolean('track_imei')->default('0');
            $table->decimal('purchase_price', 19, 2)->default('0');
            $table->decimal('sale_price', 19, 2)->default('0');
            $table->string('sku', 80)->nullable();
            $table->string('category', 40)->default('mobile_phone');
            $table->string('brand', 100)->nullable();
            $table->string('model', 150)->nullable();
            $table->smallInteger('ram_gb')->unsigned()->nullable();
            $table->smallInteger('storage_gb')->unsigned()->nullable();
            $table->string('sim_configuration', 40)->nullable();
            $table->string('warranty_type', 40)->default('shop_warranty');
            $table->string('product_code', 40)->collation('utf8mb4_bin')->nullable();
            $table->bigInteger('brand_master_data_id')->unsigned()->nullable();
            $table->bigInteger('ram_master_data_id')->unsigned()->nullable();
            $table->bigInteger('storage_master_data_id')->unsigned()->nullable();
            $table->bigInteger('sim_master_data_id')->unsigned()->nullable();
            $table->bigInteger('category_master_data_id')->unsigned()->nullable();
            $table->bigInteger('subcategory_master_data_id')->unsigned()->nullable();
            $table->dateTime('archived_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['product_code'], 'mt21_products_0');
            $table->index(['outlet_id', 'name'], 'mt21_products_1');
            $table->unique(['outlet_id', 'sku'], 'mt21_products_2');
            $table->unique(['public_id'], 'mt21_products_3');
            $table->unique(['id', 'outlet_id'], 'mt21_products_4');
        });

        Schema::create('sales', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('product_id')->unsigned();
            $table->bigInteger('outlet_id')->unsigned();
            $table->date('sale_date');
            $table->decimal('sale_price', 19, 2);
            $table->bigInteger('invoice_id')->unsigned();
            $table->integer('quantity');
            $table->decimal('total_price', 19, 2);
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->decimal('purchase_price', 19, 2)->default('0');
            $table->decimal('discount_allocated', 19, 2)->default('0');
            $table->decimal('net_total_price', 19, 2)->default('0');
            $table->decimal('profit', 19, 2)->default('0');
            $table->json('invoice_detail_options')->nullable();
            $table->json('invoice_detail_snapshot')->nullable();
        });

        Schema::create('outlet_admins', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('outlet_id')->unsigned();
            $table->bigInteger('admin_id')->unsigned();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['outlet_id', 'admin_id'], 'mt21_outlet_admins_0');
        });

        Schema::create('stock_acquisitions', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('outlet_id')->unsigned();
            $table->bigInteger('product_id')->unsigned();
            $table->string('source_type', 40);
            $table->string('business_name', 255)->nullable();
            $table->string('seller_name', 255)->nullable();
            $table->string('seller_cnic', 15)->nullable();
            $table->string('seller_phone', 20)->nullable();
            $table->text('seller_address')->nullable();
            $table->string('cnic_front_path', 255)->nullable();
            $table->string('cnic_back_path', 255)->nullable();
            $table->integer('quantity')->unsigned();
            $table->decimal('unit_purchase_price', 19, 2)->default('0');
            $table->dateTime('acquired_at', 6)->useCurrent();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->bigInteger('source_type_master_data_id')->unsigned()->nullable();
            $table->index(['seller_cnic'], 'mt21_stock_acquisitions_0');
        });

        Schema::create('stock_movements', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('product_id')->unsigned();
            $table->bigInteger('stock_unit_id')->unsigned()->nullable();
            $table->bigInteger('outlet_id')->unsigned();
            $table->string('type', 40);
            $table->integer('quantity_change');
            $table->integer('stock_before')->unsigned();
            $table->integer('stock_after')->unsigned();
            $table->string('reference_type', 80)->collation('utf8mb4_bin')->nullable();
            $table->bigInteger('reference_id')->unsigned()->nullable();
            $table->text('reason')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['product_id', 'created_at'], 'mt21_stock_movements_0');
            $table->index(['reference_type', 'reference_id'], 'mt21_stock_movements_1');
        });

        Schema::create('stock_units', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('product_id')->unsigned();
            $table->integer('unit_no')->unsigned();
            $table->string('color', 100)->nullable();
            $table->string('condition', 40)->nullable();
            $table->string('pta_status', 50)->nullable();
            $table->string('carrier_lock_status', 50)->nullable();
            $table->string('mdm_status', 40)->nullable();
            $table->decimal('purchase_price', 19, 2)->default('0');
            $table->string('status', 40)->default('in_stock');
            $table->bigInteger('invoice_id')->unsigned()->nullable();
            $table->bigInteger('sale_id')->unsigned()->nullable();
            $table->dateTime('sold_at', 6)->nullable();
            $table->text('notes')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->bigInteger('stock_acquisition_id')->unsigned()->nullable();
            $table->string('unit_code', 50)->collation('utf8mb4_bin')->nullable();
            $table->bigInteger('color_master_data_id')->unsigned()->nullable();
            $table->bigInteger('condition_master_data_id')->unsigned()->nullable();
            $table->bigInteger('pta_status_master_data_id')->unsigned()->nullable();
            $table->bigInteger('carrier_lock_master_data_id')->unsigned()->nullable();
            $table->bigInteger('mdm_status_master_data_id')->unsigned()->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->index(['product_id', 'status'], 'mt21_stock_units_0');
            $table->unique(['product_id', 'unit_no'], 'mt21_stock_units_1');
            $table->unique(['unit_code'], 'mt21_stock_units_2');
            $table->unique(['public_id'], 'mt21_stock_units_3');
            $table->unique(['id', 'product_id'], 'mt21_stock_units_4');
        });

        Schema::create('super_admins', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('name', 255);
            $table->string('email', 255);
            $table->dateTime('email_verified_at', 6)->nullable();
            $table->string('password', 255);
            $table->string('remember_token', 100)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('profile_photo', 255)->nullable();
            $table->string('business_name', 255)->nullable();
            $table->string('business_phone', 40)->nullable();
            $table->string('business_whatsapp', 40)->nullable();
            $table->text('business_address')->nullable();
            $table->string('username', 80)->nullable();
            $table->string('business_legal_name', 255)->nullable();
            $table->text('business_hours')->nullable();
            $table->json('business_identifiers')->nullable();
            $table->dateTime('archived_at', 6)->nullable();
            $table->unique(['email'], 'mt21_super_admins_0');
            $table->unique(['username'], 'mt21_super_admins_1');
        });

        Schema::create('outlets', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('name', 255);
            $table->string('email', 255)->nullable();
            $table->dateTime('email_verified_at', 6)->nullable();
            $table->string('legacy_password', 255)->nullable();
            $table->boolean('status')->default('0');
            $table->string('legacy_remember_token', 100)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('business_name', 255)->nullable();
            $table->string('business_email', 255)->nullable();
            $table->string('business_phone', 40)->nullable();
            $table->string('business_whatsapp', 40)->nullable();
            $table->text('business_address')->nullable();
            $table->char('outlet_code', 3)->collation('utf8mb4_bin')->nullable();
            $table->string('business_legal_name', 255)->nullable();
            $table->text('business_hours')->nullable();
            $table->json('business_identifiers')->nullable();
            $table->dateTime('archived_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['email'], 'mt21_outlets_0');
            $table->unique(['outlet_code'], 'mt21_outlets_1');
            $table->unique(['public_id'], 'mt21_outlets_2');
        });

        Schema::create('reservation_allocations', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('reservation_line_id')->unsigned();
            $table->bigInteger('product_id')->unsigned();
            $table->bigInteger('stock_unit_id')->unsigned()->nullable();
            $table->integer('quantity')->unsigned()->default('1');
            $table->string('active_key', 140)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('released_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->bigInteger('active_stock_unit_id')->unsigned()->storedAs('CASE WHEN released_at IS NULL THEN stock_unit_id ELSE NULL END');
            $table->unique(['active_key'], 'mt21_reservation_allocations_0');
            $table->index(['product_id', 'released_at'], 'mt21_reservation_allocations_1');
            $table->index(['reservation_line_id', 'stock_unit_id'], 'mt21_reservation_allocations_2');
            $table->unique(['active_stock_unit_id'], 'mt21_reservation_allocations_3');
        });

        Schema::create('reservation_lines', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('reservation_id')->unsigned();
            $table->string('website_order_item_id', 100);
            $table->string('product_external_id', 100)->collation('utf8mb4_bin');
            $table->string('outlet_external_id', 100)->collation('utf8mb4_bin');
            $table->string('variant_key', 100)->collation('utf8mb4_bin');
            $table->integer('quantity')->unsigned();
            $table->decimal('unit_price', 19, 2);
            $table->decimal('line_total', 19, 2);
            $table->integer('allocated_quantity')->unsigned()->default('0');
            $table->json('source_snapshot')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->bigInteger('order_item_id')->unsigned();
            $table->bigInteger('product_id')->unsigned();
            $table->bigInteger('outlet_id')->unsigned();
            $table->index(['product_external_id', 'outlet_external_id', 'variant_key'], 'mt21_reservation_lines_0');
            $table->unique(['reservation_id', 'website_order_item_id'], 'mt21_reservation_lines_1');
            $table->unique(['reservation_id', 'order_item_id'], 'mt21_reservation_lines_2');
            $table->unique(['id', 'product_id'], 'mt21_reservation_lines_3');
        });

        Schema::create('reservations', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('source', 40)->collation('utf8mb4_bin')->default('mobist-website');
            $table->string('website_order_number', 80);
            $table->uuid('reservation_reference')->collation('utf8mb4_bin');
            $table->string('state', 20)->default('active');
            $table->char('currency', 3)->default('PKR');
            $table->string('customer_name', 160);
            $table->string('customer_mobile', 20);
            $table->decimal('total_amount', 19, 2)->default('0');
            $table->dateTime('reservation_expires_at', 6)->nullable();
            $table->string('website_payment_id', 100)->nullable();
            $table->string('gateway', 40)->collation('utf8mb4_bin')->nullable();
            $table->string('transaction_reference', 160)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('paid_at', 6)->nullable();
            $table->bigInteger('invoice_id')->unsigned()->nullable();
            $table->dateTime('confirmed_at', 6)->nullable();
            $table->dateTime('released_at', 6)->nullable();
            $table->dateTime('expired_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->char('contract_hash', 64)->collation('utf8mb4_bin')->nullable();
            $table->bigInteger('order_id')->unsigned();
            $table->integer('attempt')->unsigned()->default(1);
            $table->bigInteger('outlet_id')->unsigned();
            $table->bigInteger('holding_order_id')->unsigned()->storedAs('CASE WHEN state IN (\'active\', \'held_cod\') THEN order_id ELSE NULL END');
            $table->unique(['invoice_id'], 'mt21_reservations_0');
            $table->unique(['reservation_reference'], 'mt21_reservations_1');
            $table->index(['state', 'reservation_expires_at'], 'mt21_reservations_2');
            $table->unique(['website_payment_id'], 'mt21_reservations_3');
            $table->unique(['order_id', 'attempt'], 'mt21_reservations_4');
            $table->unique(['holding_order_id'], 'mt21_reservations_5');
        });

        Schema::create('admin_audit_logs', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('user_id')->unsigned()->nullable();
            $table->string('actor_name', 180)->nullable();
            $table->string('actor_email', 190)->nullable();
            $table->string('action', 180);
            $table->string('method', 10);
            $table->string('path', 500);
            $table->json('payload')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->smallInteger('status_code')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['action'], 'mt21_admin_audit_logs_0');
            $table->index(['created_at'], 'mt21_admin_audit_logs_1');
        });

        Schema::create('digital_services', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('slug', 255)->collation('utf8mb4_bin');
            $table->string('name', 255);
            $table->string('category', 255)->nullable();
            $table->text('short_description');
            $table->text('description')->nullable();
            $table->string('price_type', 255)->default('quote');
            $table->decimal('price', 19, 2)->nullable();
            $table->boolean('is_active')->default('1');
            $table->integer('sort_order')->unsigned()->default('0');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['is_active', 'sort_order'], 'mt21_digital_services_0');
            $table->unique(['slug'], 'mt21_digital_services_1');
        });

        Schema::create('order_items', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('order_id')->unsigned();
            $table->string('item_type', 255);
            $table->bigInteger('product_listing_id')->unsigned()->nullable();
            $table->bigInteger('digital_service_id')->unsigned()->nullable();
            $table->string('external_reference', 255)->collation('utf8mb4_bin')->nullable();
            $table->string('title', 255);
            $table->text('description')->nullable();
            $table->integer('quantity')->unsigned()->default('1');
            $table->decimal('unit_price', 19, 2)->default('0');
            $table->decimal('line_total', 19, 2)->default('0');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('outlet_external_id', 100)->collation('utf8mb4_bin')->nullable();
            $table->string('outlet_name', 255)->nullable();
            $table->string('pos_variant_key', 100)->collation('utf8mb4_bin')->nullable();
            $table->json('pos_source_snapshot')->nullable();
            $table->bigInteger('product_id')->unsigned()->nullable();
            $table->bigInteger('outlet_id')->unsigned()->nullable();
            $table->bigInteger('project_quote_id')->unsigned()->nullable();
            $table->index(['order_id', 'item_type'], 'mt21_order_items_0');
            $table->index(['outlet_external_id'], 'mt21_order_items_1');
            $table->index(['pos_variant_key'], 'mt21_order_items_2');
        });

        Schema::create('orders', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('order_number', 255);
            $table->string('order_type', 255);
            $table->string('status', 255)->default('pending');
            $table->string('customer_name', 255);
            $table->string('customer_mobile', 255);
            $table->string('customer_email', 255)->nullable();
            $table->string('city', 255)->nullable();
            $table->text('delivery_address')->nullable();
            $table->string('project_reference', 255)->collation('utf8mb4_bin')->nullable();
            $table->text('notes')->nullable();
            $table->decimal('subtotal', 19, 2)->default('0');
            $table->decimal('total', 19, 2)->default('0');
            $table->char('currency', 3)->default('PKR');
            $table->string('payment_status', 255)->default('unpaid');
            $table->string('invoice_number', 255)->nullable();
            $table->dateTime('confirmed_at', 6)->nullable();
            $table->dateTime('paid_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('fulfillment_status', 40)->default('pending');
            $table->text('admin_notes')->nullable();
            $table->text('return_reason')->nullable();
            $table->string('refund_status', 40)->default('none');
            $table->dateTime('processing_at', 6)->nullable();
            $table->dateTime('ready_at', 6)->nullable();
            $table->dateTime('dispatched_at', 6)->nullable();
            $table->dateTime('completed_at', 6)->nullable();
            $table->dateTime('cancelled_at', 6)->nullable();
            $table->dateTime('returned_at', 6)->nullable();
            $table->dateTime('refunded_at', 6)->nullable();
            $table->dateTime('stock_return_confirmed_at', 6)->nullable();
            $table->bigInteger('stock_return_confirmed_by')->unsigned()->nullable();
            $table->string('pos_integration_status', 40)->default('not_requested');
            $table->string('pos_reservation_id', 100)->nullable();
            $table->dateTime('pos_reservation_expires_at', 6)->nullable();
            $table->string('pos_invoice_reference', 100)->collation('utf8mb4_bin')->nullable();
            $table->text('pos_last_error')->nullable();
            $table->dateTime('pos_last_synced_at', 6)->nullable();
            $table->bigInteger('user_id')->unsigned()->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->bigInteger('customer_id')->unsigned()->nullable();
            $table->unique(['invoice_number'], 'mt21_orders_0');
            $table->unique(['order_number'], 'mt21_orders_1');
            $table->index(['order_type', 'status'], 'mt21_orders_2');
            $table->index(['payment_status'], 'mt21_orders_3');
            $table->index(['pos_integration_status', 'pos_reservation_expires_at'], 'mt21_orders_4');
            $table->unique(['pos_reservation_id'], 'mt21_orders_5');
            $table->index(['user_id', 'created_at'], 'mt21_orders_6');
            $table->unique(['public_id'], 'mt21_orders_7');
        });

        Schema::create('payments', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('order_id')->unsigned();
            $table->string('gateway', 255)->collation('utf8mb4_bin')->default('easypaisa');
            $table->string('status', 255)->default('pending');
            $table->decimal('amount', 19, 2);
            $table->char('currency', 3)->default('PKR');
            $table->string('gateway_order_reference', 255)->collation('utf8mb4_bin')->nullable();
            $table->string('transaction_reference', 255)->collation('utf8mb4_bin')->nullable();
            $table->json('gateway_response')->nullable();
            $table->dateTime('initiated_at', 6)->nullable();
            $table->dateTime('paid_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->string('merchant', 100)->collation('utf8mb4_bin');
            $table->string('mode', 20)->collation('utf8mb4_bin');
            $table->string('attempt_key', 100)->collation('utf8mb4_bin');
            $table->index(['gateway_order_reference'], 'mt21_payments_0');
            $table->index(['gateway', 'status'], 'mt21_payments_1');
            $table->index(['transaction_reference'], 'mt21_payments_2');
            $table->unique(['public_id'], 'mt21_payments_3');
            $table->unique(['order_id', 'attempt_key'], 'mt21_payments_4');
            $table->unique(['gateway', 'merchant', 'mode', 'transaction_reference'], 'mt21_payments_5');
        });

        Schema::create('legacy_integration_events', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->uuid('event_uuid');
            $table->bigInteger('order_id')->unsigned();
            $table->string('event_type', 40);
            $table->uuid('idempotency_key')->collation('utf8mb4_bin');
            $table->json('payload');
            $table->string('status', 20)->default('pending');
            $table->integer('attempts')->unsigned()->default('0');
            $table->dateTime('available_at', 6)->nullable();
            $table->dateTime('locked_at', 6)->nullable();
            $table->dateTime('processed_at', 6)->nullable();
            $table->text('last_error')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['event_uuid'], 'mt21_legacy_integration_events_0');
            $table->unique(['idempotency_key'], 'mt21_legacy_integration_events_1');
            $table->index(['order_id', 'event_type'], 'mt21_legacy_integration_events_2');
            $table->index(['status', 'available_at'], 'mt21_legacy_integration_events_3');
        });

        Schema::create('product_reviews', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('product_listing_id')->unsigned();
            $table->bigInteger('user_id')->unsigned();
            $table->bigInteger('order_item_id')->unsigned();
            $table->tinyInteger('rating')->unsigned();
            $table->string('title', 160)->nullable();
            $table->text('body');
            $table->string('status', 20)->default('pending');
            $table->text('admin_reply')->nullable();
            $table->dateTime('approved_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['product_listing_id', 'status', 'approved_at'], 'mt21_product_reviews_0');
            $table->unique(['user_id', 'order_item_id'], 'mt21_product_reviews_1');
        });

        Schema::create('product_listings', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('external_source', 255)->default('pos');
            $table->string('external_id', 255)->collation('utf8mb4_bin')->nullable();
            $table->string('slug', 255)->collation('utf8mb4_bin');
            $table->string('name', 255);
            $table->string('brand', 255)->nullable();
            $table->string('model', 255)->nullable();
            $table->string('storage', 255)->nullable();
            $table->string('colour', 255)->nullable();
            $table->string('condition', 255)->nullable();
            $table->text('description')->nullable();
            $table->decimal('legacy_online_price', 19, 2)->nullable();
            $table->integer('legacy_stock_quantity')->unsigned()->nullable();
            $table->string('legacy_availability_status', 255)->default('unavailable');
            $table->string('warranty_summary', 255)->nullable();
            $table->string('image_url', 255)->nullable();
            $table->boolean('is_online')->default('0');
            $table->dateTime('legacy_synced_at', 6)->nullable();
            $table->json('source_metadata')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('category', 50)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->bigInteger('product_id')->unsigned();
            $table->index(['category'], 'mt21_product_listings_0');
            $table->unique(['external_source', 'external_id'], 'mt21_product_listings_1');
            $table->index(['is_online', 'legacy_availability_status'], 'mt21_product_listings_2');
            $table->unique(['slug'], 'mt21_product_listings_3');
            $table->unique(['public_id'], 'mt21_product_listings_4');
            $table->unique(['product_id'], 'mt21_product_listings_5');
        });

        Schema::create('project_quotes', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('reference', 255)->collation('utf8mb4_bin');
            $table->string('legacy_secure_token', 64)->collation('utf8mb4_bin')->nullable();
            $table->bigInteger('digital_service_id')->unsigned()->nullable();
            $table->string('client_name', 255);
            $table->string('customer_mobile', 255);
            $table->string('customer_email', 255)->nullable();
            $table->string('title', 255);
            $table->text('description')->nullable();
            $table->decimal('amount', 19, 2);
            $table->char('currency', 3)->default('PKR');
            $table->string('status', 255)->default('approved');
            $table->dateTime('expires_at', 6)->nullable();
            $table->dateTime('paid_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->bigInteger('service_request_id')->unsigned()->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->index(['customer_mobile', 'status'], 'mt21_project_quotes_0');
            $table->index(['reference', 'status'], 'mt21_project_quotes_1');
            $table->unique(['reference'], 'mt21_project_quotes_2');
            $table->unique(['legacy_secure_token'], 'mt21_project_quotes_3');
            $table->unique(['service_request_id'], 'mt21_project_quotes_4');
            $table->unique(['public_id'], 'mt21_project_quotes_5');
        });

        Schema::create('service_requests', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('reference', 255)->collation('utf8mb4_bin');
            $table->bigInteger('digital_service_id')->unsigned()->nullable();
            $table->string('customer_name', 255);
            $table->string('business_name', 255)->nullable();
            $table->string('customer_mobile', 255);
            $table->string('customer_email', 255)->nullable();
            $table->text('requirements');
            $table->string('preferred_contact', 255)->default('whatsapp');
            $table->string('status', 255)->default('new');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['reference'], 'mt21_service_requests_0');
            $table->index(['status', 'created_at'], 'mt21_service_requests_1');
            $table->unique(['public_id'], 'mt21_service_requests_2');
        });

        Schema::create('site_configuration_revisions', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('domain', 80)->collation('utf8mb4_bin');
            $table->integer('version')->unsigned();
            $table->string('state', 20);
            $table->json('snapshot');
            $table->bigInteger('created_by_user_id')->unsigned()->nullable();
            $table->bigInteger('published_by_user_id')->unsigned()->nullable();
            $table->dateTime('published_at', 6)->nullable();
            $table->bigInteger('restored_from_revision_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['domain'], 'mt21_site_configuration_revisions_0');
            $table->index(['domain', 'state'], 'mt21_site_configuration_revisions_1');
            $table->unique(['domain', 'version'], 'mt21_site_configuration_revisions_2');
            $table->index(['state'], 'mt21_site_configuration_revisions_3');
        });

        Schema::create('site_managed_pages', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('title', 190);
            $table->string('slug', 160)->collation('utf8mb4_bin');
            $table->text('content');
            $table->string('template', 40)->default('standard');
            $table->boolean('show_in_navigation')->default('0');
            $table->string('publish_state', 20)->default('draft');
            $table->dateTime('published_at', 6)->nullable();
            $table->bigInteger('created_by_user_id')->unsigned()->nullable();
            $table->bigInteger('updated_by_user_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->string('content_format', 20)->default('plain');
            $table->string('seo_title', 190)->nullable();
            $table->string('meta_description', 320)->nullable();
            $table->string('canonical_url', 500)->nullable();
            $table->string('social_title', 190)->nullable();
            $table->string('social_description', 320)->nullable();
            $table->bigInteger('social_image_media_id')->unsigned()->nullable();
            $table->boolean('is_indexable')->default('1');
            $table->string('content_purpose', 30)->default('general');
            $table->index(['content_purpose'], 'mt21_site_managed_pages_0');
            $table->index(['publish_state'], 'mt21_site_managed_pages_1');
            $table->index(['show_in_navigation'], 'mt21_site_managed_pages_2');
            $table->unique(['slug'], 'mt21_site_managed_pages_3');
            $table->index(['social_image_media_id'], 'mt21_site_managed_pages_4');
        });

        Schema::create('site_media_assets', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('disk', 60)->default('public');
            $table->string('path', 500);
            $table->string('original_name', 255);
            $table->string('mime_type', 100);
            $table->string('extension', 12);
            $table->bigInteger('byte_size')->unsigned();
            $table->integer('width')->unsigned();
            $table->integer('height')->unsigned();
            $table->decimal('aspect_ratio', 12, 6);
            $table->char('sha256', 64);
            $table->string('alt_text', 500)->nullable();
            $table->string('status', 20)->default('active');
            $table->bigInteger('uploaded_by_user_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['path'], 'mt21_site_media_assets_0');
            $table->index(['sha256'], 'mt21_site_media_assets_1');
            $table->index(['status'], 'mt21_site_media_assets_2');
        });

        Schema::create('site_media_usages', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('media_asset_id')->unsigned();
            $table->string('usage_domain', 80);
            $table->string('usage_key', 160)->collation('utf8mb4_bin');
            $table->string('entity_type', 160)->nullable();
            $table->bigInteger('entity_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['media_asset_id', 'usage_domain', 'usage_key', 'entity_type', 'entity_id'], 'mt21_site_media_usages_0');
            $table->index(['entity_type', 'entity_id'], 'mt21_site_media_usages_1');
            $table->index(['usage_domain'], 'mt21_site_media_usages_2');
        });

        Schema::create('site_navigation_items', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('key', 80)->collation('utf8mb4_bin');
            $table->bigInteger('parent_id')->unsigned()->nullable();
            $table->string('label', 120);
            $table->string('destination_type', 30);
            $table->string('destination_key', 100)->collation('utf8mb4_bin')->nullable();
            $table->json('destination_payload')->nullable();
            $table->integer('sort_order')->unsigned()->default('0');
            $table->boolean('is_visible')->default('1');
            $table->boolean('is_enabled')->default('1');
            $table->string('target_behavior', 20)->default('same_tab');
            $table->bigInteger('created_by_user_id')->unsigned()->nullable();
            $table->bigInteger('updated_by_user_id')->unsigned()->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['is_visible', 'is_enabled'], 'mt21_site_navigation_items_0');
            $table->unique(['key'], 'mt21_site_navigation_items_1');
            $table->index(['parent_id', 'sort_order'], 'mt21_site_navigation_items_2');
        });

        Schema::create('site_secret_settings', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('key', 140)->collation('utf8mb4_bin');
            $table->longText('ciphertext');
            $table->integer('version')->unsigned()->default('1');
            $table->bigInteger('updated_by_user_id')->unsigned()->nullable();
            $table->dateTime('rotated_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['key'], 'mt21_site_secret_settings_0');
        });

        Schema::create('site_settings', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('key', 120)->collation('utf8mb4_bin');
            $table->text('value')->nullable();
            $table->string('group', 60)->default('general');
            $table->string('label', 160)->nullable();
            $table->integer('sort_order')->unsigned()->default('0');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->index(['group'], 'mt21_site_settings_0');
            $table->unique(['key'], 'mt21_site_settings_1');
        });

        Schema::create('users', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('name', 255);
            $table->string('email', 255);
            $table->dateTime('email_verified_at', 6)->nullable();
            $table->string('password', 255);
            $table->string('remember_token', 100)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->boolean('is_admin')->default('0');
            $table->string('admin_role', 40)->nullable();
            $table->string('mobile', 30)->nullable();
            $table->string('profile_photo_path', 255)->nullable();
            $table->dateTime('archived_at', 6)->nullable();
            $table->index(['admin_role'], 'mt21_users_0');
            $table->unique(['email'], 'mt21_users_1');
            $table->index(['is_admin'], 'mt21_users_2');
            $table->unique(['mobile'], 'mt21_users_3');
        });

        Schema::create('customers', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('website_user_id')->unsigned()->nullable();
            $table->string('display_name', 255);
            $table->string('email', 255)->nullable();
            $table->string('mobile', 40)->nullable();
            $table->dateTime('archived_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['public_id'], 'mt21_customers_0');
            $table->unique(['website_user_id'], 'mt21_customers_1');
        });

        Schema::create('customer_source_links', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('customer_id')->unsigned();
            $table->string('source_repository', 32)->collation('utf8mb4_bin');
            $table->string('source_table', 64)->collation('utf8mb4_bin');
            $table->string('source_primary_key', 191)->collation('utf8mb4_bin');
            $table->string('verification_kind', 64)->collation('utf8mb4_bin');
            $table->string('verified_actor_type', 40)->collation('utf8mb4_bin');
            $table->bigInteger('verified_actor_id')->unsigned();
            $table->dateTime('verified_at', 6);
            $table->text('verification_reason');
            $table->unique(['source_repository', 'source_table', 'source_primary_key'], 'mt21_customer_source_links_0');
        });

        Schema::create('active_imeis', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->string('imei', 32)->collation('utf8mb4_bin');
            $table->bigInteger('stock_unit_id')->unsigned();
            $table->smallInteger('slot_no')->unsigned();
            $table->primary(['imei'], 'mt21_active_imeis_0');
            $table->unique(['stock_unit_id', 'slot_no'], 'mt21_active_imeis_1');
        });

        Schema::create('payment_receipts', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('payment_id')->unsigned();
            $table->string('gateway', 255)->collation('utf8mb4_bin');
            $table->string('merchant', 100)->collation('utf8mb4_bin');
            $table->string('mode', 20)->collation('utf8mb4_bin');
            $table->string('event_id', 255)->collation('utf8mb4_bin');
            $table->string('transaction_reference', 255)->collation('utf8mb4_bin')->nullable();
            $table->decimal('amount', 19, 2);
            $table->char('currency', 3)->collation('utf8mb4_bin')->default('PKR');
            $table->string('payload_hash', 64)->collation('utf8mb4_bin');
            $table->dateTime('received_at', 6);
            $table->dateTime('verified_at', 6);
            $table->unique(['gateway', 'merchant', 'mode', 'event_id'], 'mt21_payment_receipts_0');
            $table->unique(['gateway', 'merchant', 'mode', 'transaction_reference'], 'mt21_payment_receipts_1');
        });

        Schema::create('returns', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('invoice_id')->unsigned();
            $table->bigInteger('order_id')->unsigned()->nullable();
            $table->string('actor_type', 40)->collation('utf8mb4_bin');
            $table->bigInteger('actor_id')->unsigned();
            $table->text('reason');
            $table->string('status', 40)->collation('utf8mb4_bin');
            $table->string('idempotency_key', 100)->collation('utf8mb4_bin');
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['public_id'], 'mt21_returns_0');
            $table->unique(['actor_type', 'actor_id', 'idempotency_key'], 'mt21_returns_1');
        });

        Schema::create('return_lines', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('return_id')->unsigned();
            $table->bigInteger('sale_id')->unsigned();
            $table->bigInteger('stock_unit_id')->unsigned()->nullable();
            $table->integer('quantity')->unsigned();
            $table->string('condition', 100)->collation('utf8mb4_bin');
            $table->string('disposition', 40)->collation('utf8mb4_bin');
            $table->dateTime('accepted_at', 6)->nullable();
            $table->unique(['return_id', 'stock_unit_id'], 'mt21_return_lines_0');
        });

        Schema::create('refunds', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('payment_id')->unsigned();
            $table->bigInteger('return_id')->unsigned()->nullable();
            $table->decimal('amount', 19, 2);
            $table->char('currency', 3)->collation('utf8mb4_bin')->default('PKR');
            $table->string('status', 40)->collation('utf8mb4_bin');
            $table->string('operation_key', 100)->collation('utf8mb4_bin');
            $table->string('provider', 100)->collation('utf8mb4_bin');
            $table->string('provider_reference', 255)->collation('utf8mb4_bin')->nullable();
            $table->string('evidence_hash', 64)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->uuid('public_id')->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->unique(['public_id'], 'mt21_refunds_0');
            $table->unique(['operation_key'], 'mt21_refunds_1');
        });

        Schema::create('idempotency_requests', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('actor_scope', 191)->collation('utf8mb4_bin');
            $table->string('operation', 100)->collation('utf8mb4_bin');
            $table->string('key', 191)->collation('utf8mb4_bin');
            $table->string('request_hash', 64)->collation('utf8mb4_bin');
            $table->string('resource_type', 80)->collation('utf8mb4_bin')->nullable();
            $table->bigInteger('resource_id')->unsigned()->nullable();
            $table->string('status', 40)->collation('utf8mb4_bin');
            $table->json('response')->nullable();
            $table->dateTime('response_expires_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->dateTime('updated_at', 6)->nullable();
            $table->unique(['actor_scope', 'operation', 'key'], 'mt21_idempotency_requests_0');
        });

        Schema::create('domain_events', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->uuid('id')->collation('utf8mb4_bin');
            $table->string('aggregate_type', 80)->collation('utf8mb4_bin');
            $table->string('aggregate_id', 100)->collation('utf8mb4_bin');
            $table->bigInteger('aggregate_version')->unsigned();
            $table->string('event_type', 100)->collation('utf8mb4_bin');
            $table->json('payload');
            $table->string('operation_key', 191)->collation('utf8mb4_bin');
            $table->dateTime('lease_until', 6)->nullable();
            $table->string('lease_token', 64)->collation('utf8mb4_bin')->nullable();
            $table->integer('attempts')->unsigned()->default(0);
            $table->dateTime('next_attempt_at', 6)->nullable();
            $table->dateTime('completed_at', 6)->nullable();
            $table->dateTime('failed_at', 6)->nullable();
            $table->string('last_error_code', 100)->collation('utf8mb4_bin')->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->primary(['id'], 'mt21_domain_events_0');
            $table->unique(['operation_key'], 'mt21_domain_events_1');
            $table->index(['completed_at', 'failed_at', 'next_attempt_at', 'lease_until'], 'mt21_domain_events_2');
        });

        Schema::create('publication_versions', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->string('domain', 80)->collation('utf8mb4_bin');
            $table->bigInteger('version')->unsigned()->default(1);
            $table->dateTime('updated_at', 6)->nullable();
            $table->primary(['domain'], 'mt21_publication_versions_0');
        });

        Schema::create('document_sequences', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('namespace', 80)->collation('utf8mb4_bin');
            $table->bigInteger('outlet_id')->unsigned();
            $table->date('business_date');
            $table->bigInteger('next_sequence')->unsigned()->default(1);
            $table->unique(['namespace', 'outlet_id', 'business_date'], 'mt21_document_sequences_0');
        });

        Schema::create('resource_capabilities', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('resource_type', 80)->collation('utf8mb4_bin');
            $table->bigInteger('resource_id')->unsigned();
            $table->string('operation', 80)->collation('utf8mb4_bin');
            $table->string('token_hash', 64)->collation('utf8mb4_bin');
            $table->dateTime('expires_at', 6);
            $table->dateTime('revoked_at', 6)->nullable();
            $table->dateTime('created_at', 6)->nullable();
            $table->unique(['token_hash'], 'mt21_resource_capabilities_0');
        });

        Schema::create('migration_runs', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('input_manifest_hash', 64)->collation('utf8mb4_bin');
            $table->string('code_hash', 64)->collation('utf8mb4_bin');
            $table->string('schema_hash', 64)->collation('utf8mb4_bin');
            $table->string('target_identity', 191)->collation('utf8mb4_bin');
            $table->string('status', 40)->collation('utf8mb4_bin');
            $table->dateTime('started_at', 6);
            $table->dateTime('completed_at', 6)->nullable();
        });

        Schema::create('migration_identity_map', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->string('source_repository', 32)->collation('utf8mb4_bin');
            $table->string('source_table', 64)->collation('utf8mb4_bin');
            $table->string('source_primary_key', 191)->collation('utf8mb4_bin');
            $table->string('target_table', 64)->collation('utf8mb4_bin');
            $table->string('target_id', 191)->collation('utf8mb4_bin');
            $table->bigInteger('run_id')->unsigned();
            $table->string('row_digest', 64)->collation('utf8mb4_bin');
            $table->string('outcome', 40)->collation('utf8mb4_bin');
            $table->text('reviewed_merge_reference')->nullable();
            $table->unique(['source_repository', 'source_table', 'source_primary_key', 'target_table'], 'mt21_migration_identity_map_0');
            $table->index(['target_table', 'target_id'], 'mt21_migration_identity_map_1');
        });

        Schema::create('migration_quarantine', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('run_id')->unsigned();
            $table->string('source_repository', 32)->collation('utf8mb4_bin');
            $table->string('source_table', 64)->collation('utf8mb4_bin');
            $table->string('source_primary_key', 191)->collation('utf8mb4_bin');
            $table->text('reason');
            $table->text('evidence_reference');
            $table->text('resolution')->nullable();
        });

        Schema::create('migration_reconciliation', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('run_id')->unsigned();
            $table->string('control_name', 191)->collation('utf8mb4_bin');
            $table->text('source_value');
            $table->text('target_value');
            $table->string('result', 40)->collation('utf8mb4_bin');
            $table->string('evidence_hash', 64)->collation('utf8mb4_bin');
        });

        Schema::create('migration_source_history', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->bigInteger('run_id')->unsigned();
            $table->string('source_repository', 32)->collation('utf8mb4_bin');
            $table->string('source_migration', 255)->collation('utf8mb4_bin');
            $table->string('source_hash', 64)->collation('utf8mb4_bin');
            $table->integer('source_batch')->unsigned();
            $table->unique(['run_id', 'source_repository', 'source_migration'], 'mt21_migration_source_history_0');
        });

    }

    public function down(): void
    {
        Schema::dropIfExists('migration_source_history');
        Schema::dropIfExists('migration_reconciliation');
        Schema::dropIfExists('migration_quarantine');
        Schema::dropIfExists('migration_identity_map');
        Schema::dropIfExists('migration_runs');
        Schema::dropIfExists('resource_capabilities');
        Schema::dropIfExists('document_sequences');
        Schema::dropIfExists('publication_versions');
        Schema::dropIfExists('domain_events');
        Schema::dropIfExists('idempotency_requests');
        Schema::dropIfExists('refunds');
        Schema::dropIfExists('return_lines');
        Schema::dropIfExists('returns');
        Schema::dropIfExists('payment_receipts');
        Schema::dropIfExists('active_imeis');
        Schema::dropIfExists('customer_source_links');
        Schema::dropIfExists('customers');
        Schema::dropIfExists('users');
        Schema::dropIfExists('site_settings');
        Schema::dropIfExists('site_secret_settings');
        Schema::dropIfExists('site_navigation_items');
        Schema::dropIfExists('site_media_usages');
        Schema::dropIfExists('site_media_assets');
        Schema::dropIfExists('site_managed_pages');
        Schema::dropIfExists('site_configuration_revisions');
        Schema::dropIfExists('service_requests');
        Schema::dropIfExists('project_quotes');
        Schema::dropIfExists('product_listings');
        Schema::dropIfExists('product_reviews');
        Schema::dropIfExists('legacy_integration_events');
        Schema::dropIfExists('payments');
        Schema::dropIfExists('orders');
        Schema::dropIfExists('order_items');
        Schema::dropIfExists('digital_services');
        Schema::dropIfExists('admin_audit_logs');
        Schema::dropIfExists('reservations');
        Schema::dropIfExists('reservation_lines');
        Schema::dropIfExists('reservation_allocations');
        Schema::dropIfExists('outlets');
        Schema::dropIfExists('super_admins');
        Schema::dropIfExists('stock_units');
        Schema::dropIfExists('stock_movements');
        Schema::dropIfExists('stock_acquisitions');
        Schema::dropIfExists('outlet_admins');
        Schema::dropIfExists('sales');
        Schema::dropIfExists('products');
        Schema::dropIfExists('product_imeis');
        Schema::dropIfExists('pos_settings');
        Schema::dropIfExists('pos_media_usages');
        Schema::dropIfExists('pos_media_assets');
        Schema::dropIfExists('pos_master_data_usages');
        Schema::dropIfExists('pos_master_data_options');
        Schema::dropIfExists('pos_configuration_revisions');
        Schema::dropIfExists('pos_audit_logs');
        Schema::dropIfExists('personal_access_tokens');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('invoices');
        Schema::dropIfExists('legacy_integration_requests');
        Schema::dropIfExists('claims');
        Schema::dropIfExists('backup_records');
        Schema::dropIfExists('admins');
        Schema::dropIfExists('account_sessions');
    }
};
